/**
 * Builds the RIASEC respondent survey as a Google Form.
 * GENERATED by survey/generate_survey.php from db/seed_questions.php - do not edit by hand;
 * edit the source and regenerate so the form keeps matching the website.
 *
 * How to use: go to https://script.google.com -> New project -> paste this file ->
 * Run "buildSurvey" -> allow access. The new form's edit and response links are
 * printed in the Execution log.
 */
var TYPES = {
    "R": "Realistic",
    "I": "Investigative",
    "A": "Artistic",
    "S": "Social",
    "E": "Enterprising",
    "C": "Conventional"
};
var QUESTIONS = {
    "R": [
        "I enjoy repairing broken equipment.",
        "I like working with tools and machinery.",
        "I enjoy building or assembling things.",
        "I prefer practical tasks over theoretical discussions.",
        "I like working outdoors.",
        "I enjoy operating vehicles or heavy equipment.",
        "I am interested in construction projects.",
        "I enjoy fixing electrical or mechanical problems.",
        "I like working with plants, animals, or natural resources.",
        "I prefer physical activities to office work."
    ],
    "I": [
        "I enjoy solving complex problems.",
        "I like conducting experiments.",
        "I enjoy learning about scientific discoveries.",
        "I like analyzing information before making decisions.",
        "I enjoy researching topics in depth.",
        "I like finding patterns in data.",
        "I enjoy mathematics and logical reasoning.",
        "I am curious about how things work.",
        "I enjoy investigating causes of problems.",
        "I like studying subjects that require critical thinking."
    ],
    "A": [
        "I enjoy drawing, painting, or designing.",
        "I like expressing myself creatively.",
        "I enjoy writing stories, poems, or articles.",
        "I like creating original ideas.",
        "I enjoy performing music, dance, or theater.",
        "I prefer flexible environments over strict rules.",
        "I enjoy designing visual materials.",
        "I like exploring different forms of art.",
        "I enjoy imaginative activities.",
        "I prefer creative projects to routine tasks."
    ],
    "S": [
        "I enjoy helping people solve their problems.",
        "I like teaching others new skills.",
        "I enjoy working in teams.",
        "I like volunteering for community activities.",
        "I enjoy listening to people's concerns.",
        "I am interested in counseling or mentoring others.",
        "I enjoy caring for people.",
        "I like participating in group discussions.",
        "I enjoy motivating others.",
        "I prefer jobs that involve interacting with people."
    ],
    "E": [
        "I enjoy leading a group.",
        "I like convincing others to support my ideas.",
        "I enjoy organizing projects and events.",
        "I like taking initiative in group situations.",
        "I enjoy setting goals and achieving them.",
        "I am interested in starting a business.",
        "I enjoy making decisions for a team.",
        "I like negotiating with others.",
        "I enjoy selling products or services.",
        "I am comfortable taking risks to achieve success."
    ],
    "C": [
        "I enjoy organizing files and records.",
        "I like following established procedures.",
        "I enjoy working with numbers and data.",
        "I prefer clear instructions when completing tasks.",
        "I enjoy planning schedules and timelines.",
        "I like maintaining accurate records.",
        "I enjoy administrative or office work.",
        "I pay attention to details.",
        "I enjoy tasks that require precision.",
        "I prefer structured environments over unpredictable ones."
    ]
};
var SCALE = [
    "Dislike",
    "Slightly Dislike",
    "Neutral",
    "Slightly Enjoy",
    "Enjoy"
];
var PROGRAMS = [
    "BA Communication",
    "BS Multimedia Arts",
    "BS Computer Science",
    "BS Information Technology",
    "BS Biology",
    "BS Medical Technology",
    "BS Pharmacy",
    "BS Physical Therapy",
    "BS Psychology",
    "BS Nursing",
    "BS Accountancy",
    "BS Accounting Information System",
    "BS Business Administration Major in Financial Management",
    "BS Business Administration Major in Operations Management",
    "BS Business Administration Major in Sustainability Management",
    "BS Hospitality Management",
    "BS Tourism Management",
    "BS International Business",
    "BS Business Analytics with Artificial Intelligence",
    "BS Marketing",
    "BS Architecture",
    "BS Chemical Engineering",
    "BS Civil Engineering",
    "BS Mechanical Engineering",
    "BS Electrical Engineering",
    "BS Electronics Engineering",
    "BS Industrial Engineering",
    "BS Computer Engineering",
    "BS Aeronautical Engineering",
    "BS Aviation Management",
    "BS Marine Engineering",
    "BS Marine Transportation"
];
var CONSENT = "DATA PRIVACY NOTICE AND CONSENT\n\nYou are invited to take part in a research study for the capstone project \"[Project title]\" by [researchers' names], [program], Mapúa Malayan Colleges Laguna (MMCL), under the supervision of [adviser's name].\n\nPurpose: To collect career-interest (RIASEC) responses and intended college programs of Grade 12 students, used to build and evaluate a course recommendation model for the Career Profiling System.\n\nWhat we collect: Only your answers to 60 interest statements and your intended or preferred MCL program. We do NOT collect your name, email address, student number, or any other information that identifies you.\n\nVoluntary participation: Taking part is voluntary. You may stop at any time before submitting, and choosing not to participate will not affect your grades or standing in any way.\n\nUse, storage and retention: Responses are stored in a password-protected account accessible only to the researchers and their adviser, used only for this study, reported only in summary (aggregate) form, and deleted on or before [retention date, e.g. one year after the project's final defense].\n\nYour rights: Under the Data Privacy Act of 2012 (Republic Act No. 10173), you have the right to be informed, to object, to access, to correct, and to have your data erased. Because responses are anonymous, individual answers cannot be retrieved after submission.\n\nContact: [researcher contact email]. MMCL Data Protection Officer: [DPO email].\n\nRespondents below 18 years old may take part only if their parent or guardian has signed the consent form given separately [describe how it is distributed and collected].";
var AGE_CHOICES = [
    "I am 18 years old or older.",
    "I am below 18, and my parent/guardian has signed the consent form.",
    "I am below 18, and my parent/guardian has NOT signed the consent form."
];
var CONSENT_CHOICES = [
    "Yes, I have read the notice above and I agree to participate.",
    "No, I do not agree to participate."
];
var COURSE_QUESTION = "Which MCL program do you intend or prefer to take in college?";
var INTRO = "Rate each statement honestly, from Dislike to Enjoy, based on your genuine interest - not what you think sounds best. There are no right or wrong answers. This takes about 10-15 minutes.";

function buildSurvey() {
  var form = FormApp.create('Career Interest (RIASEC) Survey - Grade 12');
  form.setDescription('A research survey for the Career Profiling System capstone project.');
  form.setCollectEmail(false);          // no email addresses (data minimisation, RA 10173)
  form.setShuffleQuestions(false);      // keep the website's order
  form.setProgressBar(true);
  form.setAllowResponseEdits(false);
  form.setConfirmationMessage('Thank you for answering the survey. Your responses have been recorded.');

  // Section 1: data privacy notice, consent and age/guardian consent
  form.addSectionHeaderItem().setTitle('Data Privacy Notice and Consent').setHelpText(CONSENT);
  var consent = form.addMultipleChoiceItem().setTitle('Do you agree to participate in this study?').setRequired(true);
  var age = form.addMultipleChoiceItem().setTitle('Please confirm your age and consent status.').setRequired(true);

  // Sections 2-7: the 60 statements, one section per RIASEC type, in R, I, A, S, E, C order
  var firstQuestionPage = null;
  Object.keys(QUESTIONS).forEach(function (code) {
    var page = form.addPageBreakItem().setTitle(TYPES[code]).setHelpText(INTRO);
    if (!firstQuestionPage) firstQuestionPage = page;
    QUESTIONS[code].forEach(function (text, i) {
      form.addMultipleChoiceItem()
        .setTitle(text)
        .setHelpText(TYPES[code] + ' - Question ' + (i + 1) + ' out of 10')
        .setChoiceValues(SCALE)
        .setRequired(true);
    });
  });

  // Section 8: intended / preferred program (single choice from the 32 MCL programs)
  form.addPageBreakItem().setTitle('Intended College Program');
  form.addMultipleChoiceItem().setTitle(COURSE_QUESTION).setChoiceValues(PROGRAMS).setRequired(true);

  // Branching: anyone who does not consent, or is a minor without guardian consent, ends here
  consent.setChoices([
    consent.createChoice(CONSENT_CHOICES[0], FormApp.PageNavigationType.CONTINUE),
    consent.createChoice(CONSENT_CHOICES[1], FormApp.PageNavigationType.SUBMIT)
  ]);
  age.setChoices([
    age.createChoice(AGE_CHOICES[0], firstQuestionPage),
    age.createChoice(AGE_CHOICES[1], firstQuestionPage),
    age.createChoice(AGE_CHOICES[2], FormApp.PageNavigationType.SUBMIT)
  ]);

  Logger.log('Edit the form:     ' + form.getEditUrl());
  Logger.log('Share with students: ' + form.getPublishedUrl());
}
